# Copyright (C) 2016 Daniel James.
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# Use Trusty to get a reasonably recent version of Boost.
sudo: required
dist: trusty

language: c++

addons:
    apt:
        packages:
            - libboost-tools-dev

matrix:
    include:
      - compiler: gcc
        env: |
            USER_CONFIG="using gcc : : g++-4.8 -Werror --std=c++03 ;"
      - compiler: gcc
        env: |
            USER_CONFIG="using gcc : : g++-4.8 -Werror --std=c++11 ;"
      - compiler: clang
        env: |
            USER_CONFIG="using clang : : clang++ -Werror --std=c++03 ;"
      - compiler: clang
        env: |
            USER_CONFIG="using clang : : clang++ -Werror --std=c++11 ;"
      - compiler: clang
        env: |
            USER_CONFIG="using clang : : clang++ -Werror --std=c++11 -D_HAS_AUTO_PTR_ETC=0 ;"

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - touch Jamroot.jam
    - cd $HOME
    - echo $USER_CONFIG > ~/user-config.jam
    - cat ~/user-config.jam
    - wget -O boost.tar.bz2 https://dl.bintray.com/boostorg/release/1.65.0/source/boost_1_65_0.tar.bz2
    - tar -xjf boost.tar.bz2
    - mv boost_1_* boost
    - rm -r boost/boost/functional

script:
    - cd ${TRAVIS_BUILD_DIR}/test
    - bjam -q ${BJAM_TOOLSET} include=${HOME}/boost include=${TRAVIS_BUILD_DIR}/include
